default:
  default_user: qa
  default_project_url: https://github.com/Alex-Izquierdo/ci-cd-demo
  users:
    qa:
      username: qa@redhat.com
      password: password #gitleaks:allow
    admin:
      username: admin@redhat.com
      # password encrypted
      password: "!fernet:gAAAAABjD2hLMOOBcLjPgBD-6wYJgfZper2zJ5d7mEYCKUpMyZlkUNIxHJR78FPPvauuOICbr94K_NrlX2PCNkobMIljXpZD5Q=="
  http:
    host: localhost:8080
    scheme: http
    verify_ssl: False
